- name: varialbes to print
  hosts: web
  vars:
    COURSE: "Devops with AWS"
    Duration: "120 hours"
    Trainer: "Shiva"
  tasks:
  - name: print the iformation
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{Duration}}, Trainer: {{Trainer}}"