- name: varialbes to print
  hosts: web
  vars: #play level, all taks in this play have access to this
    COURSE: "Devops with AWS"
    DURATION: "120 hours"
    TRAINER: "Shiva"
  tasks:
  - name: print the iformation
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"


  - name: print the iformation again
    vars: #taks level variables
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

  - name: print the iformation again and again
        ansible.builtin.debug:
          msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"