- name: varialbe from prompt
  hots: web
  vars_prompt:
  - name: COURSE
    prompt: Please ender the course name
  - name: TRAINER
    prompt: Please enter the trainer name
  - name: DURATION
    prompt: Plese enter the duration name  
  
   tasks: 
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"
