- name: devops course informaiton
  hosts: local
  connection: local
  vars:
    course: "Devops with AWS"
    duration: 120
    topics:
     -Linux
     -shell
     -terraform
    live: true
    tools:
        ci: jenkins
        cm: ansible
        cloud: aws
  tasks:
  - name: print the course informaiton
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{ course}}. with dureation: {{ duration }},topic {{ topics }} and live: {{ live }}, tools are: {{ tools }}"